FROM google/cloud-sdk:389.0.0-alpine
RUN apk add curl \
    && curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
    && chmod a+x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl